Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Style/StringLiterals:
  Enabled: false
convention:Style/SymbolArray:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
